version: '3.3'

services:
  # service: 1
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend_network
    container_name: nodejs__rabbitmq__container

  # service: 2
  redisDB:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    networks:
      - backend_network
    volumes:
      - type: volume
        source: redis-data
        target: /data
    container_name: nodejs__redis__container

volumes:
  redis-data:


networks:
  backend_network:
    driver: bridge
