version: '3.3'

services:
  # service: 1
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend_network
    container_name: nodejs__rabbitmq__container

volumes:
  mongodb-data:

networks:
  backend_network:
    driver: bridge